title: Jordan McQueen | developer + learner
heading: Jordan McQueen
description: Thoughts, learnings, a place of persistence
exclude: [deploy.sh, deploy_website.py]
google_analytics:
theme: 
include: ['_thought']
collections:
    thought:
        output: true
        permalink: /:collection/:path/
        title: Thoughts
css_version: 1.03
